### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by monajalal** [paulu/material-seg#1]
[jalal@goku material-seg]$ python demo.py images/1189.jpg
Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    from matclass import dataset
  File "/scratch2/cs542/minc_dataset/material-seg/matclass/dataset.py", line 31, in <module>
    i: h for (h, i) in COLOR_TUPLE_TO_NETCAT.iteritems()
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by monajalal** [comment]
We changed this:
NETCAT_TO_COLOR_TUPLE = {
    #i: h for (h, i) in COLOR_TUPLE_TO_NETCAT.iteritems()
    i: h for (h, i) in COLOR_TUPLE_TO_NETCAT.items()

in  vi minc_dataset/material-seg/matclass/dataset.py

https://stackoverflow.com/a/30418498/2414957

**Comment by paulu** [comment]
FYI, I wrote and tested the code with python 2.
